# Generated by Django 6.0.2 on 2026-04-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0004_game_cover_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=255, verbose_name='Processador Mínimo')),
                ('minimum_processor', models.CharField(max_length=255, verbose_name='Processador Mínimo')),
                ('minimum_ram', models.IntegerField(default=0, verbose_name='Memória RAM Mínima')),
                ('minimum_gpu', models.CharField(max_length=255, verbose_name='GPU Mínima')),
                ('minimum_gpu_ram', models.IntegerField(default=0, verbose_name='Memória GPU Mínima')),
                ('maximum_processor', models.CharField(max_length=255, verbose_name='Processador Máximo')),
                ('maximum_ram', models.IntegerField(default=0, verbose_name='Memória RAM Máxima')),
                ('maximum_gpu', models.CharField(max_length=255, verbose_name='GPU Máxima')),
                ('maximum_gpu_ram', models.IntegerField(default=0, verbose_name='Memória GPU Máxima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='games.game', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'ordering': ['created_at'],
            },
        ),
    ]
