# Generated by Django 6.0.2 on 2026-04-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='system',
            field=models.CharField(max_length=255, verbose_name='Sistema Operacional'),
        ),
    ]
