# Generated by Django 6.0.2 on 2026-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_requirements', '0002_alter_requirement_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='released_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lançado por'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Armazenamento'),
        ),
    ]
