# Generated by Django 6.0.2 on 2026-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.IntegerField(default='2026', verbose_name='Ano')),
                ('vram', models.CharField(max_length=100, verbose_name='VRAM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPUs',
                'ordering': ['created_at'],
            },
        ),
    ]
