# Generated by Django 6.0.2 on 2026-04-10 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Nome de Jogo')),
                ('description', models.TextField(default='Sem descrição', max_length=1000, verbose_name='Descrição do jogo')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Capa do jogo')),
                ('score', models.FloatField(default=0.0, verbose_name='Pontuação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='categories.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['created_at'],
            },
        ),
    ]
