# Generated by Django 6.0.2 on 2026-04-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='cover_url',
        ),
    ]
