# Generated by Django 6.0.2 on 2026-04-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_path',
            field=models.URLField(blank=True, null=True, verbose_name='Caminho da imagem'),
        ),
    ]
