# Generated by Django 6.0.2 on 2026-04-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_cover_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_path',
            field=models.CharField(blank=True, null=True, verbose_name='Caminho da imagem'),
        ),
    ]
