# Generated by Django 6.0.2 on 2026-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_cover_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de lançamento'),
        ),
    ]
