# Generated by Django 6.0.2 on 2026-04-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('games', '0006_game_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='games', to='categories.category', verbose_name='Categoria'),
        ),
    ]
