# Generated by Django 6.0.2 on 2026-04-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=255, verbose_name='Processador')),
                ('memory_ram', models.IntegerField(max_length=100, verbose_name='Memória RAM')),
                ('disk', models.CharField(max_length=100, verbose_name='SSD/HDD')),
                ('disk_space', models.IntegerField(max_length=100, verbose_name='Espaço em Disco')),
                ('gpu_name', models.CharField(max_length=255, verbose_name='Placa de Vídeo')),
                ('gpu_memory', models.IntegerField(max_length=100, verbose_name='Mémoria da Placa de Vídeo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['created_at'],
            },
        ),
    ]
