# Generated by Django 6.0.2 on 2026-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='disk',
            field=models.IntegerField(default=0, verbose_name='SSD/HDD'),
        ),
        migrations.AlterField(
            model_name='player',
            name='disk_space',
            field=models.IntegerField(default=0, verbose_name='Espaço em Disco'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gpu_memory',
            field=models.IntegerField(default=0, verbose_name='Mémoria da Placa de Vídeo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='memory_ram',
            field=models.IntegerField(default=0, verbose_name='Memória RAM'),
        ),
    ]
