# Generated by Django 6.0.2 on 2026-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_disk_alter_player_disk_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='disk',
            field=models.CharField(max_length=50, verbose_name='SSD/HDD'),
        ),
    ]
