# Generated by Django 6.0.2 on 2026-04-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_disk'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_path',
            field=models.CharField(blank=True, null=True, verbose_name='Avatar caminho'),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar URL'),
        ),
    ]
