# Generated by Django 6.0.2 on 2026-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_avatar_path_player_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='unit',
            field=models.CharField(default='GB', max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
